"""Add body to Task

Revision ID: 1c26471c77a8
Revises: 52974bd0155a
Create Date: 2017-01-08 00:18:15.234331

"""

# revision identifiers, used by Alembic.
revision = '1c26471c77a8'
down_revision = '52974bd0155a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('body', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'body')
    ### end Alembic commands ###
