"""empty message

Revision ID: 2edb0edecbd3
Revises: df3efb607c6d
Create Date: 2017-01-24 19:33:48.648273

"""

# revision identifiers, used by Alembic.
revision = '2edb0edecbd3'
down_revision = 'df3efb607c6d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statuses')
    op.add_column('tasks', sa.Column('responsible', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'responsible')
    op.create_table('statuses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), nullable=True),
    sa.Column('label', sa.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###
