"""Fix public field in User

Revision ID: 52974bd0155a
Revises: a46a911c694f
Create Date: 2017-01-07 22:04:01.425888

"""

# revision identifiers, used by Alembic.
revision = '52974bd0155a'
down_revision = 'a46a911c694f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public', sa.Boolean(create_constraint=False), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'public')
    ### end Alembic commands ###
