"""empty message

Revision ID: df3efb607c6d
Revises: a7a06f9adfe0
Create Date: 2017-01-22 20:48:25.889901

"""

# revision identifiers, used by Alembic.
revision = 'df3efb607c6d'
down_revision = 'a7a06f9adfe0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    ### end Alembic commands ###
